version: '2.4'
services:
    server:
        build:
            context: ../
            dockerfile: ./docker/gpu.Dockerfile
            target: dev
        # https://github.com/NVIDIA/nvidia-docker/wiki#do-you-support-docker-compose
        runtime: nvidia
        ports: 
            - "5000:5000"
        volumes:
            - ../results:/src/results
            - ../upload:/src/upload
            - /tmp/openimages_v4__ssd__mobilenet_v2:/model_ssd
            - /tmp/faster_rcnn_openimages_v4_inception_resnet_v2:/model_faster_rcnn
            - ../code:/src/code
        environment:
            # https://stackoverflow.com/a/51362214
            - PYTHONUNBUFFERED=1
            - DEBUG=true
            - MODULE
            # - OCR_SERVER=192.168.0.5:5002
    ocr:
        image: ghcr.io/koralowiec/ocr-server:latest
        ports: 
            - "5001:5000"
        environment:
            - PYTHONUNBUFFERED=1