version: '2.4'
services:
    predict-api:
        build:
            context: ../
            dockerfile: ./docker/gpu.Dockerfile
            target: dev
        # https://github.com/NVIDIA/nvidia-docker/wiki#do-you-support-docker-compose
        runtime: nvidia
        ports: 
            - "5002:5000"
        volumes:
            - /tmp/openimages_v4__ssd__mobilenet_v2:/model_ssd
            - /tmp/faster_rcnn_openimages_v4_inception_resnet_v2:/model_faster_rcnn
            - ../code:/src/code
        environment:
            # https://stackoverflow.com/a/51362214
            - PYTHONUNBUFFERED=1
            - MODULE
            # - DEBUG=true